"""players cache and quota

Revision ID: 0001
Revises:
Create Date: 2026-09-29 09:57:34.848461
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hp_cache",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "hp_daily_usage",
        sa.Column("day", sa.String(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("live_calls", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("day", "endpoint"),
    )
    op.create_table(
        "hp_quota",
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("quota_limit", sa.Integer(), nullable=False),
        sa.Column("remaining", sa.Integer(), nullable=False),
        sa.Column("reset_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("endpoint"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hp_quota")
    op.drop_table("hp_daily_usage")
    op.drop_table("hp_cache")
    # ### end Alembic commands ###
